### PR TITLE
[levenshtein][bug] Fix bug when # of changes exceeds max length of text

### LINKED ISSUE #46: Digital transform errors
when transform 15233 to 9151 or reverse，in the LevenshteinUtils，method computeColumnActions has mistake，turn the number to 152335 & 915

### PR DESCRIPTION
**Pull request by jinatonic**
Closes #46

### CODE REVIEW

File: ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java [hunk 1]
```diff
@@ -60,38 +61,42 @@
...
 
         // Reverse trace the matrix to compute the necessary actions
-        int i = numRows - 1;
-        int j = numCols - 1;
-        int resultIndex = resultLength - 1;
-        while (resultIndex >= 0) {
-            if (i == 0) {
+        final List<Integer> resultList = new ArrayList<>(resultLength * 2);
+        int row = numRows - 1;
+        int col = numCols - 1;
```
Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java]: love the name chanes

File: ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java [hunk 2]
```diff
@@ -60,38 +61,42 @@
...
             }
-            resultIndex--;
         }
 
+        final int resultSize = resultList.size();
+        final int[] result = new int[resultSize];
+        for (int i = 0; i < resultSize; i++) {
+            result[resultSize - 1 - i] = resultList.get(i);
+        }
         return result;
```
Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java]: would it be painful to make this method's return type List<Int>? would avoid needing this conversion loop here and the quickreturn above could return Collections.emptyList()

Comment (jinatonic) [inline ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java]: yeah good point i'll just return them in list

Comment (jinatonic) [inline ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java]: uh hm just realized that the above can't return empty list because it needs to return the number of columns with no modifications, and this iteration also adds the updates in reverse since we do reverse trace of the matrix to get the modifications. eh i'll just leave it for now lol.

Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/LevenshteinUtils.java]: :shipit:
