### PR TITLE
Fix debounce when setting the same text on ticker

### LINKED ISSUE #63: ticker is unable to smoothly transition during resize
OnePlus One A0001
Android 6.0.1
Cyanogen OS 13.1.2

There's a bug that impacts the smoothness of the animations/transitions. It happens when the ticker needs to resize the dollar value string, for example, when it transitions from above $100 to below $100, or from above $10 to below $10. I've recorded a video of my screen to demonstrate the issue on my device:

https://www.dropbox.com/s/y4k3f3u6jb3wulm/device-2017-09-21-104722.mp4

This has been happening for well over a year, maybe longer. When will this be resolved?

### PR DESCRIPTION
**Pull request by jinatonic**
closes #63

### CODE REVIEW

File: ticker/src/main/java/com/robinhood/ticker/TickerView.java [hunk 1]
```diff
@@ -280,13 +280,13 @@ public void setText(String text) {
      * @param animate whether to animate to text.
      */
     public synchronized void setText(String text, boolean animate) {
-        this.text = text;
-        final char[] targetText = text == null ? new char[0] : text.toCharArray();
-
-        if (columnManager.shouldDebounceText(targetText)) {
+        if (text.equals(this.text)) {
```
Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/TickerView.java]: we need to guard against nulls here. might be a good opportunity to add nullability annotations, but might be out of scope of this diff
