### PR TITLE
Measurement optimizations and remeasure after animation completes

### LINKED ISSUE #15: wrap_content doesn't work when set value from a larger number to a smaller number
wrap_content doesn't work when set value from a larger number to a smaller number.
lets assume || is a textview, change number from 1234567 to 123, the width of the textview turns out like below

|1234567|
|123　　   |

What I think it supposed to be is like below

|1234567|
|123|

### PR DESCRIPTION
**Pull request by jinatonic**
- Do not call `requestLayout` when the content measurement do not affect the view's measurement (e.g. when the measurements are `EXACTLY`).
- Set the desired with to the target width once the animation completes.
- Force re-layout after animation completes so that the width/height matches the displayed text.

Closes #15

### CODE REVIEW

File: ticker/src/main/java/com/robinhood/ticker/TickerView.java [hunk 1]
```diff
@@ -227,7 +239,6 @@ public synchronized void setText(String text, boolean animate) {
         }
 
         columnManager.setText(targetText, animate);
-        columnManager.setAnimationProgress(animate ? 0f : 1f);
```
Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/TickerView.java]: We're now not calling `setAnimationProgress(0)` at the beginning of the animation. I assume this is fine since the animator itself should start by calling 0, but just want to double check that there's nothing missing.

File: ticker/src/main/java/com/robinhood/ticker/TickerView.java [hunk 2]
```diff
@@ -359,6 +372,28 @@ public void setGravity(int gravity) {
         }
     }
 
+    /**
+     * Enables/disables the flag to animate measurement changes. If this flag is enabled, any
+     * animation that changes the content's text width (e.g. 9999 -> 10000) will have the view's
+     * measured width animated along with the text width. However, a side effect of this is that
+     * the entering/exiting character might get truncated by the view's view bounds as the width
+     * shrinks or expands.
```
Comment (danh32) [inline ticker/src/main/java/com/robinhood/ticker/TickerView.java]: Let's add a warning in here that this causes a measure/layout pass for each animation frame and may cause performance to degrade.

File: ticker/src/main/java/com/robinhood/ticker/TickerView.java (hunk 1 above)
Comment (jinatonic) [inline ticker/src/main/java/com/robinhood/ticker/TickerView.java]: Yeah this is intentional as the animator should call `setAnimationProgress(0f)`.
